config/routes.rb
Rails.application.routes.draw do

  ## Top page for application
  root 'base#index'

  ## API
  use_doorkeeper
  scope module: :api do
    scope '/v1', as: 'v1' do
      resources :users, only: [:index, :show, :update]
    end
  end

  ## User authentication
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users/sign_up_confirm' => 'users/registrations#sign_up_confirm'
    get 'users/redirect_oauth/:provider' => 'users/omniauth_callbacks#redirect_oauth', as: :redirect_oauth
  end
  resources :users, only: [:index, :show]

  ## My settings
  get 'settings/profile' => 'settings#profile', as: :settings_profile
  patch 'settings/profile' => 'settings#update_profile'
  get 'settings/oauth' => 'settings#oauth', as: :settings_oauth
  get 'settings/oauth/remove/:provider' => 'settings#oauth_remove', as: :settings_oauth_remove

  ## Contact form
  resources :contact, only: [:index, :create]

  ## Admin
  namespace :admin do
    root 'base#index'
    resources :users do
      post :login, on: :member
    end
  end

  ## Static pages
  get ':path' => 'static_pages#static'

  ## 404 Not Found
  get '*unmatched_route' => 'application#raise_not_found!'

end

app/models/user.rb
# == Schema Information
#
# Table name: users # ユーザーマスタ
#
#  id                     :integer          not null, primary key  # ユーザーマスタ
#  key                    :string           not null               # 固有キー
#  name                   :string           default(""), not null  # ユーザー名
#  nick_name              :string           default(""), not null  # ニックネーム
#  email                  :string           default(""), not null  # メールアドレス
#  encrypted_password     :string           default(""), not null  # パスワード(ハッシュ値)
#  reset_password_token   :string                                  # パスワードリセットトークン
#  reset_password_sent_at :datetime                                # パスワードリセット要求日時
#  remember_created_at    :datetime                                # 次回自動指定でのログイン日時
#  sign_in_count          :integer          default("0"), not null # ログイン回数
#  current_sign_in_at     :datetime                                # 今回ログイン日時
#  last_sign_in_at        :datetime                                # 前回ログイン日時
#  current_sign_in_ip     :string                                  # 今回アクセス元IP
#  last_sign_in_ip        :string                                  # 前回アクセス元IP
#  confirmation_token     :string                                  # 登録確認トークン
#  confirmed_at           :datetime                                # 登録確認済み日時
#  confirmation_sent_at   :datetime                                # 登録確認要求日時
#  unconfirmed_email      :string                                  # 未確認メールアドレス
#  twitter_uid            :string                                  # TwitterアカウントUID
#  facebook_uid           :string                                  # FacebookアカウントUID
#  google_uid             :string                                  # GoogleアカウントUID
#  failed_attempts        :integer          default("0"), not null # 認証失敗回数
#  unlock_token           :string                                  # アカウントロック解除トークン
#  locked_at              :datetime                                # アカウントロック日時
#  image_file_name        :string                                  # 画像ファイル名
#  image_content_type     :string                                  # 画像MIMEタイプ
#  image_file_size        :integer                                 # 画像ファイルサイズ
#  image_updated_at       :datetime                                # 画像更新日時
#  bio                    :text                                    # 自己紹介
#  note                   :text                                    # メモ
#  created_at             :datetime         not null               # 作成日時
#  updated_at             :datetime         not null               # 更新日時
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_created_at            (created_at)
#  index_users_on_email                 (email)
#  index_users_on_name                  (name)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_unlock_token          (unlock_token) UNIQUE
#  index_users_on_updated_at            (updated_at)
#

#= User accounts

class User < ActiveRecord::Base
  include HashKey

  extend FriendlyId
  friendly_id :key

  include Garage::Representer
  include Garage::Authorizable
  property :id
  property :key
  property :name
  property :nick_name
  property :email
  property :bio
  property :created_at
  property :updated_at
  link(:self) { v1_user_url(self.id) }

  default_scope { order created_at: :desc }
  scope :enabled, -> { where 'confirmed_at is not null' }

  has_many :users_roles, dependent: :destroy
  has_many :roles, through: :users_roles

  devise :database_authenticatable, :registerable, :recoverable,
    :rememberable, :trackable, :confirmable,
    :omniauthable, omniauth_providers: [:facebook, :twitter, :google_oauth2]

  has_attached_file :image,
    styles: { avatar_lg: '256x256#' ,avatar_sm: '48x48#' }
  validates_attachment_size :image, less_than: 1.megabytes,
    message: I18n.t('errors.messages.too_large')
  validates_attachment_content_type :image,
    content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'],
    message: I18n.t('errors.messages.invalid_content_type')

  validates :email, presence: true
  validates :email, uniqueness: { allow_blank: true }
  validates :password, confirmation: true
  validates :password, length: { minimum: 8, allow_blank: true }
  validates :name, length: { maximum: 30, allow_blank: true }
  validates :name, uniqueness: { allow_blank: true }
  validates :nick_name, length: { maximum: 30, allow_blank: true }
  validates :bio, length: { maximum: 1000, allow_blank: true }
  validates :note, length: { maximum: 1000, allow_blank: true }
  validates :twitter_uid, uniqueness: { allow_blank: true }
  validates :facebook_uid, uniqueness: { allow_blank: true }
  validates :google_uid, uniqueness: { allow_blank: true }

  # Permissins for API (:index)
  def self.build_permissions(perms, other, target)
    perms.permits! :read
  end

  # Permissins for API (:show, :create, :update, :destroy)
  def build_permissions(perms, other)
    perms.permits! :read
    perms.permits! :write if self == other
  end

  # Find or add user with Facebook OAuth
  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    if signed_in_resource
      user = signed_in_resource
      user.update_attributes(facebook_uid: auth.uid)
    else
      user = find_by(facebook_uid: auth.uid)
      unless user
        user = create(
          nick_name: auth.extra.raw_info.name,
          facebook_uid: auth.uid,
          email: auth.info.email,
          image: auth.info.image + '?type=large',
          confirmed_at: Time.now
        )
      end
    end
    user
  end

  # Find or add user with Twitter OAuth
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    if signed_in_resource
      user = signed_in_resource
      user.update_attributes(twitter_uid: auth.uid)
    else
      user = find_by(twitter_uid: auth.uid)
      unless user
        user = create(
          nick_name: auth.extra.raw_info.name,
          twitter_uid: auth.uid,
          image: auth.info.image.gsub('_normal', ''),
          confirmed_at: Time.now
        )
      end
    end
    user
  end

  # Find or add user with Google OAuth
  def self.find_for_google_oauth(auth, signed_in_resource=nil)
    if signed_in_resource
      user = signed_in_resource
      user.update_attributes(google_uid: auth.uid)
    else
      user = find_by(google_uid: auth.uid)
      unless user
        user = create(
          nick_name: auth.extra.raw_info.name,
          google_uid: auth.uid,
          email: auth.info.email,
          image: auth.info.image,
          confirmed_at: Time.now
        )
      end
    end
    user
  end

  # OAuth user does not require email
  def email_required?
    super && facebook_uid.blank? && twitter_uid.blank? && google_uid.blank?
  end

  # OAuth user does not require password
  def password_required?
    super && facebook_uid.blank? && twitter_uid.blank? && google_uid.blank?
  end

  # Even if email is not set, you can reconfirm that
  def reconfirmation_required?
    self.class.reconfirmable && @reconfirmation_required # && !self.email.blank?
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end
    clean_up_passwords
    update_attributes(params, *options)
  end

  def screen_name
    if nick_name.present?
      return nick_name
    else
      email =~ /(.*)@.*/
      return $1
    end
  end
  def to_s
    screen_name
  end

  def has_role?(role_code=:any)
    if role_code == :any
      ! roles.empty?
    else
      roles.find_by(code: role_code.to_s) ? true : false
    end
  end

end

app/controllers/admin/users_controller.rb
#= (Admin) Users

class Admin::UsersController < Admin::BaseController
  include CrudController

  model User
  search :name, :nick_name, :email
  destroy :cautious
  permit :key, :name, :nick_name, :email, :image,
    :password, :password_confirmation, role_ids: []

  def record_params
    params = super
    if action_name == 'update' && params[:password] == ''
      return params.delete_if {|k, v|
        ['password', 'password_confirmation'].include?(k)}
    else
      return params
    end
  end

  def set_attributes(record, attrs)
    super
    record.skip_confirmation!
    record.skip_reconfirmation!
  end

  def login
    if current_user.valid_password?(params[:password])
      user = User.friendly.find(params[:id])
      sign_in user
      flash[:notice] = t('views.admin.users.signed_in', user: user)
      redirect_to root_path
    else
      flash[:alert] = t('views.admin.users.invalid_password')
      redirect_to admin_user_path
    end
  end

end

app/controllers/api/users_controller.rb
#= REST API for User

class Api::UsersController < Api::BaseController
  include Garage::RestfulActions

  validates :index do
    integer :page, description: 'Parameter for pagination.'
    integer :per_page, description: 'Parameter for pagination.'
  end

  def require_resources
    @resources = User.enabled
  end

  def require_resource
    @resource = User.enabled.find(params[:id])
  end

  def update_resource
    @resource.update_attributes!(user_params)
  end

  def user_params
    params.permit(
      :name, :nick_name, :email, :password, :bio)
  end

  def respond_with_resources_options
    { paginate: true }
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
#= OAuth Callbacks

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'], current_user)
    if @user.errors.present?
      flash[:alert] = @user.errors.full_messages.join
      redirect_to session[:previous_url]
    elsif @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Facebook'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env['omniauth.auth'], current_user)
    if @user.errors.present?
      flash[:alert] = @user.errors.full_messages.join
      redirect_to session[:previous_url]
    elsif @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Twitter'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.twitter_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.find_for_google_oauth(request.env['omniauth.auth'], current_user)
    if @user.errors.present?
      flash[:alert] = @user.errors.full_messages.join
      redirect_to session[:previous_url]
    elsif @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_oauth2_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def redirect_oauth
    breadcrumbs.clear
  end

end

app/controllers/users/omniauth_controller.rb
#= OAuth Callbacks

class Users::OmniauthController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_facebook_oauth(request.env['omniauth.auth'], current_user)
    if @user.errors.present?
      flash[:alert] = @user.errors.full_messages.join
      redirect_to session[:previous_url]
    elsif @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Facebook'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env['omniauth.auth'], current_user)
    if @user.errors.present?
      flash[:alert] = @user.errors.full_messages.join
      redirect_to session[:previous_url]
    elsif @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Twitter'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.twitter_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.find_for_google_oauth(request.env['omniauth.auth'], current_user)
    if @user.errors.present?
      flash[:alert] = @user.errors.full_messages.join
      redirect_to session[:previous_url]
    elsif @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_oauth2_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def redirect_oauth
    breadcrumbs.clear
  end

end

app/controllers/users/registrations_controller.rb
#= Custom for Devise::RegistrationsController

class Users::RegistrationsController < Devise::RegistrationsController

  def update_resource(resource, params)
    if current_user.encrypted_password.present?
      resource.update_with_password(params)
    else
      # Password not required when no password
      resource.update_without_current_password(
        params.permit(:password, :password_confirmation, :email))
    end
  end

  def after_sign_up_path_for(resource)
    new_session_path(resource)
  end

  def after_inactive_sign_up_path_for(resource)
    users_sign_up_confirm_path
  end

  def sign_up_confirm
    add_breadcrumb t('views.devise.registrations.new.title'), new_user_registration_path(resource)
    @title = t('views.devise.registrations.sign_up_confirm.title')
    flash.notice = nil
  end

  def after_update_path_for(resource)
    edit_registration_path(resource)
  end

  def destroy
    if ! params[:confirmed]
      flash[:alert] = t('crud.destroy.required_confirm')
    elsif ! (current_user && current_user.valid_password?(params[:password]))
      flash[:alert] = t('crud.destroy.invalid_password')
    end
    if flash[:alert]
      redirect_to edit_registration_path(resource_name)
    else
      super
    end
  end

end

app/controllers/users_controller.rb
#= Users

class UsersController < ApplicationController

  def index
    @title = breadcrumbs.last.name
  end

  def show
    @user = User.friendly.find(params[:id])
    @title = @user
  end

end

app/views/admin/users/_form.html.slim
= render 'partial/errors', record: record
= form_for([:admin, record], html: {class: 'form-horizontal edit-form'}) do |f|
  .nav-tabs-custom
    ul.nav.nav-tabs
      li.active
        a href="#tab_1" data-toggle="tab"
          = t 'views.admin.users.basic'
    .tab-content
      .tab-pane.active#tab_1
        = f.bootstrap_text :email
        = f.bootstrap_text :name
        = f.bootstrap_text :nick_name
        = f.bootstrap_paperclip :image, :avatar_sm
        = f.bootstrap_collection_checkboxes :role_ids, Role.all, :id, :name
        = f.bootstrap_password :password, autocomplete: 'off'
        = f.bootstrap_password :password_confirmation, autocomplete: 'off', placeholder: t('helpers.input.password_confirmation')
      = f.bootstrap_submits t('helpers.submit.' + {'new'=>'create','create'=>'create','edit'=>'update','update'=>'update'}[action_name])

app/views/admin/users/edit.html.slim
= render 'form', record: @record
= render 'partial/destroy_cautious', record: @record

app/views/admin/users/index.html.slim
- content_for :pagetool_right
  a href=new_admin_user_path type="button" class=['btn', 'btn-default', ('disabled' if cannot? :create, User)].compact.join(' ')
    span.fa.fa-plus>
    = t 'crud.new.title'

- content_for :pagetool_left
  form action=admin_users_path class="form-inline"
    .input-group
      input.form-control#search-keyword type="text" placeholder=t('helpers.search.keyword') name="q" value=params[:q]
      span.input-group-btn
        button.btn.btn-default type="submit"
          span.fa.fa-search

- if @records.empty?
  p = t 'views.messages.not_found'

- else
  .box
    .box-body.no-padding.table-responsive
      table.table.table-hover.silent-link
        thead
          tr
            th = User.model_name.human
            th.text-right = User.human_attribute_name(:created_at)
        tbody
          - @records.each do |record|
            tr onclick="location.href='#{admin_user_path(record)}';" style="cursor:pointer;" class=('warning' unless record.confirmed_at)
              td
                => image_tag record.image(:avatar_sm), width: 24, height: 24, alt: record.screen_name
                = link_to record, admin_user_path(record)
              td.text-right
                = l record.created_at

  = render 'partial/paginate', records: @records

app/views/admin/users/new.html.slim
= render 'form', record: @record

app/views/admin/users/show.html.slim
- content_for :pagetool_left
  a href=edit_admin_user_path class=['btn', 'btn-default', ('disabled' if cannot? :update, User)].compact.join(' ')
    span.fa.fa-pencil>
    = t 'crud.edit.title'

p
  img.img-responsive src=@record.image(:avatar_lg) width="128" height="128" alt=@record.screen_name

.nav-tabs-custom

  ul.nav.nav-tabs
    li.active
      a href="#tab_1" data-toggle="tab"
        = t 'views.admin.users.basic'

  .tab-content
    - unless @record.confirmed_at
      .callout.callout-warning
        = t 'views.admin.users.unconfirmed'
    .tab-pane.active#tab_1
      .table-responsive
        table.table.table-bordered
          tr
            th.col-xs-4 = User.human_attribute_name :email
            td = @record.email
          tr
            th = User.human_attribute_name :name
            td = @record.name
          tr
            th = User.human_attribute_name :nick_name
            td = @record.nick_name
          tr
            th = User.human_attribute_name :roles
            td = @record.roles.map {|role| role.name}.join(', ')
          tr
            th = User.human_attribute_name :sign_in_count
            td = @record.sign_in_count
          tr
            th = User.human_attribute_name :current_sign_in_at
            td = l @record.current_sign_in_at if @record.current_sign_in_at
          tr
            th = User.human_attribute_name :current_sign_in_ip
            td = @record.current_sign_in_ip
          tr
            th = User.human_attribute_name :last_sign_in_at
            td = l @record.last_sign_in_at if @record.last_sign_in_at
          tr
            th = User.human_attribute_name :last_sign_in_ip
            td = @record.last_sign_in_ip
          tr
            th = User.human_attribute_name :created_at
            td = l @record.created_at
          tr
            th = User.human_attribute_name :updated_at
            td = l @record.updated_at

.box
  .box-header
    h3.box-title = t 'views.admin.users.sign_in_as'
  .box-body
    = form_tag login_admin_user_path(@record), class: 'form-inline'
      input.form-control> type="password" name="password" placeholder=t('views.admin.users.your_password')
      button.btn.btn-default = t 'views.devise.sessions.new.submit'