config/routes.rb
Rails.application.routes.draw do

  ## Top page for application
  root 'base#index'

  ## API
  use_doorkeeper
  scope module: :api do
    scope '/v1', as: 'v1' do
      resources :users, only: [:index, :show, :update]
    end
  end

  ## User authentication
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  devise_scope :user do
    get 'users/sign_up_confirm' => 'users/registrations#sign_up_confirm'
    get 'users/redirect_oauth/:provider' => 'users/omniauth_callbacks#redirect_oauth', as: :redirect_oauth
  end
  resources :users, only: [:index, :show]

  ## My settings
  get 'settings/profile' => 'settings#profile', as: :settings_profile
  patch 'settings/profile' => 'settings#update_profile'
  get 'settings/oauth' => 'settings#oauth', as: :settings_oauth
  get 'settings/oauth/remove/:provider' => 'settings#oauth_remove', as: :settings_oauth_remove

  ## Contact form
  resources :contact, only: [:index, :create]

  ## Admin
  namespace :admin do
    root 'base#index'
    resources :users do
      post :login, on: :member
    end
  end

  ## Static pages
  get ':path' => 'static_pages#static'

  ## 404 Not Found
  get '*unmatched_route' => 'application#raise_not_found!'

end

app/views/layouts/_admin_menu.html.slim
li class=('active' if controller.is_a? Admin::UsersController)
  a href=admin_users_path
    i.fa.fa-user.fa-fw>
    span = User.model_name.human
li
  a href="/oauth/applications" target="_blank"
    i.fa.fa-key.fa-fw>
    span OAuth2 Provider

app/views/layouts/admin.html.slim
doctype html
html lang="ja"

  head
    title
      = [@title, Const::PRODUCT].compact.join(' - ')
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"

    = stylesheet_link_tag 'admin'
    = csrf_meta_tags
    == yield :head

  body.skin-blue.sidebar-mini
    .wrapper

      - if notice
        .sysmsg.alert.alert-info.alert-dismissable
          span.fa.fa-info>
          button.close data-dismiss="alert" ×
          = notice
      - if alert
        .sysmsg.alert.alert-danger.alert-dismissable
          span.fa.fa-warning>
          button.close data-dismiss="alert" ×
          = alert

      header.main-header
        a.logo href=admin_root_path
          span.logo-mini
            | SA
          span.logo-lg
            = Const::PRODUCT

        nav.navbar.navbar-static-top role="navigation"
          a.sidebar-toggle href="javascript:void(0);" data-toggle="offcanvas" role="button"
            span.sr-only Toggle navigation

      aside.main-sidebar
        section.sidebar
          ul.sidebar-menu
            li.header MENU
            = render 'layouts/admin_menu'

      .content-wrapper
        - if @title.present? || breadcrumbs.present?
          section.content-header
            h1 = @title
            - if breadcrumbs.present?
              ol.breadcrumb
                = render_breadcrumbs builder: CustomBreadcrumbsBuilder
        section.content
          - pagetool_left = yield :pagetool_left
          - pagetool_right = yield :pagetool_right
          - if pagetool_left.present? || pagetool_right.present?
            .row
              .col-sm-6.pagetool-left
                == pagetool_left
              .col-sm-6.pagetool-right
                == pagetool_right
          == yield

      footer.main-footer
        .pull-right
          | version
          =< Const::VERSION
        div
          => Const::PRODUCT
          = Const::COPYRIGHT

    = render 'partial/legacy_browsers'
    = javascript_include_tag 'admin'
    = javascript_include_tag 'AdminLTE/app' if Rails.env != 'test'
    javascript:
      I18n.defaultLocale = '#{I18n.default_locale}';
      I18n.locale = '#{I18n.locale}';
    == yield :foot

app/views/layouts/application.html.slim
doctype html
html

  head
    title
      - if request.path == root_path
        = @title
      - else
        = "#{@title} - " if @title
        = Const::PRODUCT
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
    == yield :head

  body

    - if notice
      .sysmsg.alert.alert-info
        button.close.fa.fa-times data-dismiss="alert"
        = notice
    - if alert
      .sysmsg.alert.alert-danger
        button.close.fa.fa-times data-dismiss="alert"
        = alert

    nav.navbar.navbar-default.navbar-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href=root_path
            = Const::PRODUCT
        .collapse.navbar-collapse.navbar-ex1-collapse
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li.dropdown
                a.dropdown-toggle data-toggle="dropdown" href="javascript:void(0);"
                  img.avatar> src=current_user.image(:avatar_sm) alt=current_user.screen_name title=current_user.screen_name
                  => current_user.screen_name
                  span.caret
                ul.dropdown-menu
                  li = link_to t('views.users.show.my_page'), user_path(current_user)
                  li = link_to t('views.settings.title'), settings_profile_path
                  li.divider
                  li = link_to t('views.devise.sessions.destroy.title'), destroy_session_path(resource_name)
                  - if current_user.has_role?(:admin)
                    li.divider
                    li = link_to t('views.admin.title'), admin_root_path
            - else
              li class=('active' if controller_name == 'registrations')
                = link_to t('views.devise.registrations.new.title'), new_registration_path(resource_name)
              li class=('active' if controller_name == 'sessions')
                = link_to t('views.devise.sessions.new.title'), new_session_path(resource_name)

    == yield :cover

    .container#content
      .row.row-offcanvas.row-offcanvas-left
        - sidebar = yield :sidebar
        - if !sidebar.empty?
          .col-sm-3.sidebar-offcanvas#sidebar role="navigation"
            .sidebar-nav
              == sidebar
          .col-sm-9
            .container-right.content
              .visible-xs
                button.btn.btn-default.btn-sm type="button" data-toggle="offcanvas"
                  span.fa.fa-angle-left>
                  | MENU
              - if @title && request.path != root_path
                .page-header
                  .pull-right
                    = yield :pagetool
                  h1
                    => @title
                    - if @subtitle
                      small = @subtitle
              == yield
        - else
          .container.content
            - if @title && request.path != root_path
              .page-header
                .pull-right
                  = yield :pagetool
                h1
                  => @title
                  - if @subtitle
                    small = @subtitle
            == yield

    .container
      - if breadcrumbs.present?
        .footer-breadcrumb
          - if request.path != root_path
            ol.breadcrumb
              - add_breadcrumb @title if breadcrumbs.last.name != @title
              = render_breadcrumbs builder: CustomBreadcrumbsBuilder

      /[if lt IE9]
        .alert.alert-warning = t 'views.messages.ie_caution'
      noscript
        .alert.alert-danger = t 'views.messages.noscript_caution'

    .footer
      .container
        .row
          .col-sm-8
            = Const::COPYRIGHT
          .col-sm-4

    = render 'partial/legacy_browsers'
    = javascript_include_tag 'application'
    javascript:
      I18n.defaultLocale = '#{I18n.default_locale}';
      I18n.locale = '#{I18n.locale}';
    == yield :foot